### ISSUE TITLE
Qt based ZeroConf implementation

### ISSUE THREAD

**Issue by maggu2810** [sikoragmbh/qtbonjour#2]
Hello,
I have searched for a Qt based ZeroConf implementation.
You are using dns_sd.h and link against it (in your .pri).
Am I right, that this is a Qt wrapper, only and not a solution in Qt?

A pure Qt implementation (I look for one for the service discovery, before I will implement that myself) will work on all supported platform (Linux, Android, Windows, OS X, iOS, ...). If we depend on "dns_sd.h" this will not work on Android (am I right?).

**Comment by sikoragmbh** [comment]
This is a very simple wrapper for Apples DNSSD lib I found in the Mumble project. Another Zeroconf implementation is [Avahi](http://www.avahi.org/ ). Maybe you can compile Avahi for Android. There's a dnssd compatibility library shipped with avahi, which provides "dns_sd.h".
I do not support this QtBonjour lib anymore and will probably take it down in the near future.
